use_frameworks!

platform :ios, '8.0'

target 'PromiseYTKNetwork_Example' do
  pod 'PromiseYTKNetwork', :path => '../'

  target 'PromiseYTKNetwork_Tests' do
    inherit! :search_paths

    
  end
end
